owner: beglov
repo: upptime

sites:
#  - name: telemed
#    url: https://telemed.rosminzdrav.ru/users/sign_in
  - name: ftms2
    url: https://ftms2.rosminzdrav.ru/users/sign_in
  - name: vko-kmt
    url: http://tms.vko-kmt.ru/users/sign_in
  - name: ddn
    url: http://ddn.vko-kmt.ru/users/sign_in
  - name: fil
    url: http://fil.vko-kmt.ru/users/sign_in
  - name: ddn52
    url: http://ddn52.vko-kmt.ru/users/sign_in
  - name: API Docs
    url: http://tms.vko-kmt.ru:8080/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
