owner: beglov
repo: upptime

sites:
  - name: TEST
    url: http://tms-ttc.ru/
  - name: VN
    url: http://vn.tms-ttc.ru/
  - name: MEDBOX
    url: http://tms-ttc.ru:8081/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
